---
- name: Install and configure Kubernetes
  hosts: localhost
  become: yes
  become_method: sudo
  vars:
    ansible_become_password: "mg"
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Download the Kubernetes apt key
      become: yes
      shell: curl -fsSL https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes.gpg

    - name: Add Kubernetes apt repository
      block:
        - name: Add Kubernetes apt repository
          apt_repository:
            repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
            state: present

      rescue:
        - name: Add Kubernetes apt repository rescue block
          debug:
            msg: "This task has been failed in the Add Kubernetes apt repository"

    - name: Install necessary components
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common

    - name: Install Kubernetes components
      snap:
        name: "{{ item }}"
        state: present
      with_items:
        - kubelet
        - kubeadm
        - kubectl
