---
- name: Host A HTML page with Apache2
  hosts: localhost
  become_method: sudo
  become: yes
  vars:
    ansible_become_password: "mg"
  tasks:
    - name: Install Apache2
      become: yes
      package:
        name: apache2
        state: present
    - name: root directory exists
      file:
        path: /var/www/html
        state: directory
      become: yes
    - name: Copy HTML file to remote host
      copy:
        src: index.html
        dest: /var/www/html/index.html
    - name: Install Apache2
      become: yes
      package:
        name: apache2
        state: present
    - name: Start Apache service
      become: yes
      service:
        name: apache2
        state: started
        enabled: yes
