---
- name: Configure LAMP stact
  hosts: test_servers
  # hosts: localhost
  become_method: sudo
  become: yes
  # remote_user: root
  vars_files:
    - secret.yaml
  tasks:
    # - name: sudo systemctl stop apache2
    #   ansible.builtin.shell:
    #     cmd: sudo systemctl stop apache2
      
    - name: sudo apt purge apache2 libapache2-mod-php php*
      ansible.builtin.shell:
        cmd: sudo apt purge apache2 libapache2-mod-php php* -y
    
    - name: sudo rm -rf /etc/apache2 /etc/php /var/www/html 
      ansible.builtin.shell:
        cmd: sudo rm -rf /etc/apache2 /etc/php /var/www/html

    - name: sudo apt autoremove
      ansible.builtin.shell:
        cmd: sudo apt autoremove -y