---
- name: Configure LAMP stact
  hosts: test_servers
  # hosts: localhost
  become_method: sudo
  become: yes
  # remote_user: root
  vars_files:
    - secret.yaml
  tasks:
    - name: Install MySQL ans PHP
      apt:
        update_cache: yes
        name:
          - mysql-server
          - mysql-client
          - python3-mysqldb
          - php7.4
          - php7.4-mysql
          - pip
        state: present

    - name: Update apt package cache
      apt:
        update_cache: yes

    - name: Add PHP PPA
      apt_repository:
        repo: ppa:ondrej/php
        state: present

    - name: Update apt package cache
      apt:
        update_cache: yes

    - name: Install PHP 7.4
      apt:
        name: php7.4
        state: present

    - name: Install PyMySQL
      pip:
        name: pymysql
        state: present

    - name: Sets the root password
      mysql_user:
        name: root
        password: "{{ mysql_root_password }}"
        login_unix_socket: /var/run/mysqld/mysqld.sock

    - name: Create a database
      become: true
      mysql_db:
        name: "{{ mysql_db }}"
        state: present
        login_user: root
        login_password: "{{ mysql_root_password }}"

    - name: Create a MySQL user
      mysql_user:
        name: "{{ mysql_user }}"
        password: "{{ mysql_user_password }}"
        priv: "{{ mysql_db }}.*:ALL"
        state: present
        login_user: root
        login_password: "{{ mysql_root_password }}"

    - name: Create MySQL database
      become: true
      mysql_db:
        login_user: root
        login_password: "{{ mysql_root_password }}"
        name: "{{ mysql_db }}"
        state: present

    - name: Create 'users' table
      become: true
      mysql_query:
        login_unix_socket: /var/run/mysqld/mysqld.sock
        login_user: root
        login_password: "{{ mysql_root_password }}"
        # mysql_db: "{{ mysql_db }}"
        query: >
          CREATE TABLE IF NOT EXISTS people.users (
            email VARCHAR(255) PRIMARY KEY,
            password VARCHAR(255) NOT NULL
          )

    - name: Insert data into MySQL table
      mysql_query:
        login_user: "{{ mysql_user }}"
        login_password: "{{ mysql_user_password }}"
        login_host: localhost
        login_port: 3306
        login_db: "{{ mysql_db }}"
        query: "INSERT IGNORE INTO people.users (email, password) VALUES ('user@gmail.com', 'user@1234');"

    - name: Install Apache
      package:
        name: apache2
        state: present

    - name: Start Apache Service
      service:
        name: apache2
        state: started
        enabled: true

    - name: Start Apache Service in background
      ansible.builtin.systemd:
        name: apache2
        state: started
        no_block: yes

    - name: Copy index.html and index.php files
      copy:
        src: "{{ item.src }}"
        dest: "/var/www/html/{{ item.dest }}"
      with_items:
        - { src: "login.php", dest: "login.php" }
        - { src: "index.html", dest: "index.html" }
        - { src: "info.php", dest: "info.php" }
        - { src: "index.php", dest: "index.php" }
        - { src: "basic.php", dest: "basic.php" }
        - { src: "basic.html", dest: "basic.html" }


      
    - name: Restart Apache Service
      service:
        name: apache2
        state: started
        enabled: true

    - name: Execute update command
      ansible.builtin.shell:
        cmd: sudo a2enmod php7.4

    - name: Restart Apache Service
      service:
        name: apache2
        state: started
        enabled: true
          
    
    - name: Update apt package cache
      apt:
        update_cache: yes

    - name: Install HAProxy
      package:
        name: haproxy
        state: present

    - name: Configure HAProxy
      template:
        src: haproxy.cfg.j2
        dest: /etc/haproxy/haproxy.cfg
      notify: Restart HAProxy
      
  handlers:
    - name: restart apache
      service:
        name: apache2
        state: restarted

    - name: Restart HAProxy
      service:
        name: haproxy
        state: restarted