---
- name: Configure Load Balancer Servers
  hosts: localhost
  become: yes
  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes

    - name: Install HAProxy
      package:
        name: haproxy
        state: present

    - name: Configure HAProxy
      template:
        src: haproxy.cfg.j2
        dest: /etc/haproxy/haproxy.cfg
      notify: Restart HAProxy
      
  handlers:
    - name: Restart HAProxy
      service:
        name: haproxy
        state: restarted