---
- name: Configure Web Servers
  hosts: localhost
  become_method: sudo
  remote_user: root
  become: yes
  tasks:
    - name: Install Apache
      package:
        name: apache2
        state: present

    - name: Start Apache Service
      service:
        name: apache2
        state: started
        enabled: true

    - name: Copy index.html
      copy:
        src: "{{ item.src }}"
        dest: /var/www/html/"{{ item.dest }}"
      with_items:
      - { src: "success.html", dest: "success.html.html" }
      - { src: "index.php", dest: "index.php" }
      

    - name: Restart Apache Service
      service:
        name: apache2
        state: started
        enabled: true

