---
- name: Remove all the exited Docker containers
  # hosts: test_servers
  hosts: localhost
  become: yes
  become_method: sudo
  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes
        
    - name: Get IDs of all running containers
      shell: docker ps -q
      register: running_containers

    - name: Stop all running containers
      shell: docker stop {{ item }}
      with_items: "{{ running_containers.stdout_lines }}"
      
    - name: Get ID of the container
      shell: docker ps -aqf "name=my_container_name"
      register: container_id

    # - name: Delete the container
    #   docker_container:
    #     name: "{{ container_id.stdout }}"
    #     state: absent

    - name: List all Docker containers in the exited state
      command: docker ps -a --filter status=exited --format "{{ '{{' }}.ID{{ '}}' }}"
      register: docker_exited_containers
      ignore_errors: true

    - name: Remove exited Docker containers
      command: docker rm {{ item }}
      loop: "{{ docker_exited_containers.stdout_lines }}"