---
- name: Update and Install the Jenkins
  hosts: test_servers
  # hosts: localhost
  become: yes
  become_method: sudo

  tasks:
    - name: Update apt packages
      apt:
        update_cache: yes
        
    - name: Install Java (Jenkins dependency)
      apt:
        name: openjdk-21-jdk
        state: present

    - name: Add Jenkins repository key to the system
      apt_key:
        url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
        state: present

    - name: Add the Jenkins Repo
      ansible.builtin.command:
        cmd: sh -c 'echo deb https://pkg.jenkins.io/debian-stable binary/ > /etc/apt/sources.list.d/jenkins.list'

    - name: Update apt cache with new Jenkins repo
      apt:
        update_cache: yes

    - name: Install Jenkins
      apt:
        name: jenkins
        state: latest

    - name: Ensure Jenkins is started and enabled
      service:
        name: jenkins
        state: started
        enabled: yes

    - name: Install unzip package via apt cmd
      apt:
        name: unzip
        state: present

    - name: Execute update command
      ansible.builtin.shell:
        cmd: sudo apt-get update && sudo apt-get install gnupg software-properties-common

    - name: Update apt package cache
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name: "{{ item }}"
        state: present
      with_items:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common

    - name: Docker Installation step starts here !!
      apt:
        update_cache: yes
        
    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Update apt package cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install Docker CE
      apt:
        name: docker-ce
        state: present

    - name: Install Docker Compose
      apt:
        name: docker-compose
        state: present

    - name: Update apt package cache
      apt:
        update_cache: yes

    - name: Ensure Docker service is running
      service:
        name: docker
        state: started

    - name: Run SonarQube container
      command: >
        docker run -d
        -p 9000:9000
        --name sonarqube
        -v sonarqube_data:/opt/sonarqube/data
        -v sonarqube_extensions:/opt/sonarqube/extensions
        -v sonarqube_logs:/opt/sonarqube/logs
        -v sonarqube_temp:/opt/sonarqube/temp
        sonarqube:latest