---
- name: Install required packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common
    - python3
    - python3-venv
    - python3-pip
    - gnupg
    - lsb-release

- name: Update apt packages
  apt:
    update_cache: yes

- name: Install unzip package
  apt:
    name: unzip
    state: present
